# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Bingo

on:
  release:
    types: [created]  # 当有新Release创建时触发
  workflow_dispatch:   # 允许手动触发

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置Java环境
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 授予Gradle执行权限
      - name: Make gradlew executable
        run: chmod +x gradlew

      # 使用Gradle构建项目
      - name: Build with Gradle
        run: ./gradlew clean build

      # 上传产物到Release
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/libs/*.jar          # Java库文件
            build/outputs/apk/*.apk    # Android APK文件（可选）
          draft: false                 # 发布正式版（draft: true则为草稿）
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
